### ISSUE TITLE
How to bind optional nested XML elements?

### ISSUE THREAD

**Issue by alexdma** [sparql-generate/sparql-generate#106]
Hi,
Elaborating on my example from #105 (thanks @maximelefrancois86 for the response!), I expanded my XML example to include a nested `obj` element, but only once 
```xml
<root>

  <obj>
    <a5000>08155906</a5000>
  </obj>

  <obj>
    <a5001>08030751</a5001>
  </obj>

  <obj>
    <a5000>08061733</a5000>
    <obj>
      <a5001>08061733,T,001</a5001>
    </obj>
  </obj>

</root>
```
There are triples I want to generate for every `obj`, but also special triples that related the nested ones with `ex:contains`:
```ttl
@prefix ex: <http://example.com/> .
<http://example.com/object/08155906>  ex:hasID  <http://example.com/id/a5000/08155906> .
<http://example.com/object/08030751>  ex:hasID  <http://example.com/id/a5001/08030751> .
<http://example.com/object/08061733>  ex:hasID  <http://example.com/id/a5000/08061733> 
    ; ex:contains <http://example.com/object/08061733%2CT%2C001>  .
<http://example.com/object/08061733%2CT%2C001>  ex:hasID  <http://example.com/id/a5001/08061733%2CT%2C001> .
```
So I need my iterator to pick up every `<obj>`, but I also need a separate binding for nested ones. I tried the following (note that, as per #105, I repeat the VALUES clause twice).

```sparql
PREFIX ex: <http://example.com/> .
GENERATE { 
    <http://example.com/object/{?id}>  ex:hasID  <http://example.com/id/{?idtype}/{?id}>
        ; ex:contains <http://example.com/object/{?idsub}> .
}
SOURCE <http://example.com/document.xml> AS ?source
ITERATOR ite:XPath(?source, "//obj", "/obj/obj" ) AS ?obj ?subobj
WHERE {
     VALUES ?idtype { "a5000" "a5001" }
     VALUES ?idtype2 { "a5000" "a5001" }
     BIND( fun:XPath(?obj, "/obj/{ ?idtype }/text()"  ) AS ?id )
     BIND( fun:XPath(?subobj, "/obj/{ ?idtype2 }/text()"  ) AS ?idsub )
} 
```
As expected, `subobj` is bound only once in the batch (third tuple), but the other cases still seem to result in a fatal exception.
```
28:19,025 main TRACE fr.mines_stetienne.ci.sparql_generate.engine.SelectPlan:116 - Executing select query:
[...]
SELECT  ?source ?obj ?subobj ?idtype ?idtype2 ?id ?idsub (iri(concat("http://example.com/object/", encode_for_uri(?id))) AS ?44c23fce) (iri(concat("http://example.com/id/", encode_for_uri(?idtype), "/", encode_for_uri(?id))) AS ?d46d6a96) (iri(concat("http://example.com/object/", encode_for_uri(?idsub))) AS ?d1e0e04a)
WHERE
  { VALUES ?idtype { "a5000" "a5001" }
    VALUES ?idtype2 { "a5000" "a5001" }
    BIND(fun:XPath(?obj, concat("/obj/", str(?idtype), "/text()")) AS ?id)
    BIND(fun:XPath(?subobj, concat("/obj/", str(?idtype2), "/text()")) AS ?idsub)
  }
 
with initial values:
VALUES ( ?source ?obj ?subobj ) {
  ( "<?xml version=\"1.0\" encoding=\"windows-12\n ... obj>\n\n</root>\n\n"^^<http://www.iana.org/assignments/media-types/application/xml> "<?xml version=\"1.0\" encoding=\"UTF-8\"?><o\n ... 5000>\n\t\t\t</obj>"^^<http://www.iana.org/assignments/media-types/application/xml> UNDEF )
  ( "<?xml version=\"1.0\" encoding=\"windows-12\n ... obj>\n\n</root>\n\n"^^<http://www.iana.org/assignments/media-types/application/xml> "<?xml version=\"1.0\" encoding=\"UTF-8\"?><o\n ... 5001>\n\t\t\t</obj>"^^<http://www.iana.org/assignments/media-types/application/xml> UNDEF )
  ( "<?xml version=\"1.0\" encoding=\"windows-12\n ... obj>\n\n</root>\n\n"^^<http://www.iana.org/assignments/media-types/application/xml> "<?xml version=\"1.0\" encoding=\"UTF-8\"?><o\n ... /obj>\n\t\t\t</obj>"^^<http://www.iana.org/assignments/media-types/application/xml> "<?xml version=\"1.0\" encoding=\"UTF-8\"?><o\n ... 001>\n\t\t\t\t</obj>"^^<http://www.iana.org/assignments/media-types/application/xml> )
  ( "<?xml version=\"1.0\" encoding=\"windows-12\n ... obj>\n\n</root>\n\n"^^<http://www.iana.org/assignments/media-types/application/xml> "<?xml version=\"1.0\" encoding=\"UTF-8\"?><o\n ... 001>\n\t\t\t\t</obj>"^^<http://www.iana.org/assignments/media-types/application/xml> UNDEF )
}
28:19,029 main ERROR fr.mines_stetienne.ci.sparql_generate.engine.SelectPlan:153 - Error while executing 
[...]
SELECT  ?source ?obj ?subobj ?idtype ?idtype2 ?id ?idsub (iri(concat("http://example.com/object/", encode_for_uri(?id))) AS ?44c23fce) (iri(concat("http://example.com/id/", encode_for_uri(?idtype), "/", encode_for_uri(?id))) AS ?d46d6a96) (iri(concat("http://example.com/object/", encode_for_uri(?idsub))) AS ?d1e0e04a)
WHERE
  {  }

org.apache.jena.sparql.ARQInternalErrorException: check(?subobj, null): null node value
	at org.apache.jena.sparql.engine.binding.BindingBase.checkPair(BindingBase.java:124)
	at org.apache.jena.sparql.engine.binding.BindingHashMap.checkAdd(BindingHashMap.java:96)
	at org.apache.jena.sparql.engine.binding.BindingHashMap.add(BindingHashMap.java:86)
	at fr.mines_stetienne.ci.sparql_generate.engine.SelectPlan.lambda$mergeValues$1(SelectPlan.java:217)
	... more
28:19,033 main WARN  fr.mines_stetienne.ci.sparql_generate.engine.IteratorPlan:133 - Unanticipated exception for ITERATOR http://w3id.org/sparql-generate/iter/XPath [?source, "//obj", "/obj/obj"] AS [?obj, ?subobj]
fr.mines_stetienne.ci.sparql_generate.SPARQLExtException: Error while executing SELECT Query 
[...]
SELECT  ?source ?obj ?subobj ?idtype ?idtype2 ?id ?idsub (iri(concat("http://example.com/object/", encode_for_uri(?id))) AS ?44c23fce) (iri(concat("http://example.com/id/", encode_for_uri(?idtype), "/", encode_for_uri(?id))) AS ?d46d6a96) (iri(concat("http://example.com/object/", encode_for_uri(?idsub))) AS ?d1e0e04a)
WHERE
  {  }

	at fr.mines_stetienne.ci.sparql_generate.engine.SelectPlan.exec(SelectPlan.java:154)
	at fr.mines_stetienne.ci.sparql_generate.engine.RootPlan.execSelectPlan(RootPlan.java:433)
	at fr.mines_stetienne.ci.sparql_generate.engine.RootPlan.execIteratorAndSourcePlans(RootPlan.java:416)
	at fr.mines_stetienne.ci.sparql_generate.engine.RootPlan.lambda$execIteratorAndSourcePlans$1(RootPlan.java:410)
	at fr.mines_stetienne.ci.sparql_generate.engine.IteratorPlan$Batches.batchComplete(IteratorPlan.java:223)
	at fr.mines_stetienne.ci.sparql_generate.engine.IteratorPlan$Batches.add(IteratorPlan.java:157)
	at fr.mines_stetienne.ci.sparql_generate.engine.IteratorPlan.lambda$exec$0(IteratorPlan.java:129)
	at fr.mines_stetienne.ci.sparql_generate.iterator.IteratorFunctionBase.exec(IteratorFunctionBase.java:29)
	at fr.mines_stetienne.ci.sparql_generate.iterator.IteratorStreamFunctionBase.exec(IteratorStreamFunctionBase.java:99)
	at fr.mines_stetienne.ci.sparql_generate.engine.IteratorPlan.exec(IteratorPlan.java:129)
	at fr.mines_stetienne.ci.sparql_generate.engine.RootPlan.execIteratorAndSourcePlans(RootPlan.java:407)
	at fr.mines_stetienne.ci.sparql_generate.engine.RootPlan.execIteratorAndSourcePlans(RootPlan.java:403)
	at fr.mines_stetienne.ci.sparql_generate.engine.RootPlan.exec(RootPlan.java:381)
	at fr.mines_stetienne.ci.sparql_generate.engine.RootPlan.execGenerateStream(RootPlan.java:209)
	at fr.mines_stetienne.ci.sparql_generate.engine.RootPlan.execGenerate(RootPlan.java:177)
	at fr.mines_stetienne.ci.sparql_generate.cli.SPARQLExtCli.execGenerate(SPARQLExtCli.java:350)
	at fr.mines_stetienne.ci.sparql_generate.cli.SPARQLExtCli.exec(SPARQLExtCli.java:245)
	at fr.mines_stetienne.ci.sparql_generate.cli.SPARQLExtCli.main(SPARQLExtCli.java:165)
Caused by: org.apache.jena.sparql.ARQInternalErrorException: check(?subobj, null): null node value
	at org.apache.jena.sparql.engine.binding.BindingBase.checkPair(BindingBase.java:124)
	at org.apache.jena.sparql.engine.binding.BindingHashMap.checkAdd(BindingHashMap.java:96)
	at org.apache.jena.sparql.engine.binding.BindingHashMap.add(BindingHashMap.java:86)
	at fr.mines_stetienne.ci.sparql_generate.engine.SelectPlan.lambda$mergeValues$1(SelectPlan.java:217)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at fr.mines_stetienne.ci.sparql_generate.engine.SelectPlan.lambda$mergeValues$2(SelectPlan.java:217)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at fr.mines_stetienne.ci.sparql_generate.engine.SelectPlan.lambda$mergeValues$3(SelectPlan.java:215)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at fr.mines_stetienne.ci.sparql_generate.engine.SelectPlan.mergeValues(SelectPlan.java:214)
	at fr.mines_stetienne.ci.sparql_generate.engine.SelectPlan.augmentQuery(SelectPlan.java:185)
	at fr.mines_stetienne.ci.sparql_generate.engine.SelectPlan.exec(SelectPlan.java:121)
	... 17 more

```
If we are confined to XPath 1, I suppose I cannot use the question mark operator for optionals, like `/obj/obj?`

I have tried to only iterate over `//obj` and get nested objects in a BIND clause, like so:
```
WHERE {
# ...
BIND( fun:XPath(?obj, "/obj/obj/{ ?idtype2 }/text()"  ) AS ?idsub )
}
```
But on my large use case XML file this is proving extremely slow.

Where could the mistake be in my generate rule?

Thanks

**Comment by alexdma** [comment]
This might be of interest: if I remove the node name requirement of #105 and sacrifice the VALUES clauses, `idtype` and `idtype2`, it completes without throwing exceptions.
```
PREFIX ex: <http://example.com/>
GENERATE { 
    <http://example.com/object/{?id}>  ex:hasID  <http://example.com/id/a5000/{?id}>
        ; ex:contains <http://example.com/object/{?idsub}> .
}
SOURCE <http://example.com/docs/fotothek.sample2.xml> AS ?source
ITERATOR ite:XPath(?source, "//obj", "/obj/obj" ) AS ?obj ?subobj
WHERE {
     BIND( fun:XPath(?obj, "/obj/a5000/text()"  ) AS ?id )
     BIND( fun:XPath(?subobj, "/obj/a5001/text()"  ) AS ?idsub )
} 
```
Of course, not all the triples are generated (the second `obj` will be skipped). Having to generate all the bindings of the VALUES clauses, even re-adding only one without using it, seems to break it. Have we found a bug possibly?

**Comment by maximelefrancois86** [comment]
Thank you, that's right, there was a small bug hidden in 

``` 
	at fr.mines_stetienne.ci.sparql_generate.engine.SelectPlan.lambda$mergeValues$1(SelectPlan.java:217)
```

Now the query runs as expected
