### ISSUE TITLE
Exception when reading null value in SQL iterator

### ISSUE THREAD

**Issue by aliariff** [sparql-generate/sparql-generate#135]
When the result of SQL query contains a null value, an exception occurred:

```
Caused by: java.lang.NullPointerException: Argument to NodeFactory.createLiteral is null
	at java.base/java.util.Objects.requireNonNull(Objects.java:246)
	at org.apache.jena.graph.NodeFactory.createLiteral(NodeFactory.java:84)
	at org.apache.jena.sparql.expr.nodevalue.NodeValueString.makeNode(NodeValueString.java:58)
	at org.apache.jena.sparql.expr.NodeValue.asNode(NodeValue.java:877)
	at fr.mines_stetienne.ci.sparql_generate.engine.IteratorPlan$Batches.lambda$0(IteratorPlan.java:184)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at fr.mines_stetienne.ci.sparql_generate.engine.IteratorPlan$Batches.getListBinding(IteratorPlan.java:176)
	at fr.mines_stetienne.ci.sparql_generate.engine.IteratorPlan$Batches.add(IteratorPlan.java:164)
	at fr.mines_stetienne.ci.sparql_generate.engine.IteratorPlan.lambda$0(IteratorPlan.java:135)
	at fr.mines_stetienne.ci.sparql_generate.iterator.IteratorFunctionBase.exec(IteratorFunctionBase.java:29)
	at fr.mines_stetienne.ci.sparql_generate.iterator.IteratorStreamFunctionBase.exec(IteratorStreamFunctionBase.java:99)
	at fr.mines_stetienne.ci.sparql_generate.engine.IteratorPlan.exec(IteratorPlan.java:135)
	at fr.mines_stetienne.ci.sparql_generate.engine.RootPlan.execIteratorAndSourcePlans(RootPlan.java:407)
	at fr.mines_stetienne.ci.sparql_generate.engine.RootPlan.exec(RootPlan.java:381)
	at fr.mines_stetienne.ci.sparql_generate.engine.RootPlan.execGenerateStream(RootPlan.java:209)
	at fr.mines_stetienne.ci.sparql_generate.engine.RootPlan.execGenerateStream(RootPlan.java:188)
```

Suggestion: 
SQL_ITER should also handle a null value, like the other iterators:
- https://github.com/sparql-generate/sparql-generate/blob/master/sparql-generate-csv/src/main/java/fr/mines_stetienne/ci/sparql_generate/csv/ITER_CSV.java#L192-L193
- https://github.com/sparql-generate/sparql-generate/blob/master/sparql-generate-json/src/main/java/fr/mines_stetienne/ci/sparql_generate/json/ITER_JSONSurfer.java#L262-L265

**Comment by maximelefrancois86** [comment]
Agreed
