### ISSUE TITLE
XML conversion errors because of file size

### ISSUE THREAD

**Issue by cgrain** [sparql-generate/sparql-generate#138]
I tried using a simple conversion on a small-ish XML file (4000 LOC), and it fails with an error (Exception in thread "main" java.lang.StackOverflowError) which suggests it errors because of the size of the file. By checking (i.e. removing parts of the document until it worked), I confirmed that the issue was indeed the file size. I understand that there should be a limit to the file size, but: 
1. It should fail gracefully, i.e. return an understandable error-message, 
2. And more importantly, a 4k LOC ( 287 kB) XML file is way too little. 
It seems that the function calls are recursive, which may be the reason for the blow-up. 
Full debug output:
```
06:58,175 main DEBUG fr.mines_stetienne.ci.sparql_generate.stream.SPARQLExtStreamManager:133 - Locator LocatorFileAccept(/**** REDACTED ****/test) found: **** REDACTED ****\query.rqg with accept: application/vnd.sparql-generate
06:58,288 main DEBUG fr.mines_stetienne.ci.sparql_generate.engine.PlanFactory:152 - Query has embedded expressions:
**** REDACTED ****

06:58,291 main TRACE fr.mines_stetienne.ci.sparql_generate.query.SPARQLExtQuery:747 - after normalizeXExpr: BASE    <http://example.com/>
**** REDACTED ****

06:58,300 main TRACE fr.mines_stetienne.ci.sparql_generate.query.SPARQLExtQuery:758 - after normalizeBNode: BASE    <http://example.com/>
**** REDACTED ****

06:58,300 main TRACE fr.mines_stetienne.ci.sparql_generate.query.SPARQLExtQuery:769 - after normalizeAggregates: BASE    <http://example.com/>
**** REDACTED ****

06:58,300 main TRACE fr.mines_stetienne.ci.sparql_generate.engine.PlanFactory:168 - Making plan for query without embedded expressions
**** REDACTED ****

06:58,322 main TRACE fr.mines_stetienne.ci.sparql_generate.engine.PlanFactory:351 - Generated SELECT query
**** REDACTED ****

06:58,322 main DEBUG org.apache.jena.shared.LockMRSW:57 - Lock : main
06:58,322 main DEBUG org.apache.jena.shared.LockMRSW:57 - Lock : main
06:58,528 main DEBUG fr.mines_stetienne.ci.sparql_generate.FileConfigurations:166 - No default graph provided: <***REDACTED***\default.ttl> Code: 4/UNWISE_CHARACTER in PATH: The character matches no grammar rules of URIs/IRIs. These characters are permitted in RDF URI References, XML system identifiers, and XML Schema anyURIs.
06:58,549 main DEBUG org.apache.jena.shared.LockMRSW:57 - Lock : main
06:58,550 main DEBUG org.apache.jena.shared.LockMRSW:57 - Lock : main
06:58,552 main INFO  fr.mines_stetienne.ci.sparql_generate.engine.RootPlan:364 - Starting execution
06:58,552 main DEBUG fr.mines_stetienne.ci.sparql_generate.engine.SourcePlan:98 - Start SOURCE http://example.com/example.xml AS ?source
06:58,555 main TRACE fr.mines_stetienne.ci.sparql_generate.engine.SourcePlan:103 - ... resolved to SOURCE <http://example.com/example.xml> ACCEPT */* AS ?source
06:58,555 main DEBUG fr.mines_stetienne.ci.sparql_generate.stream.SPARQLExtStreamManager:133 - Locator LocatorFileAccept(/***REDACTED***/test) found: documentset/example.xml with accept: */*
06:58,560 main DEBUG fr.mines_stetienne.ci.sparql_generate.engine.SourcePlan:126 - Exec SOURCE http://example.com/example.xml AS ?source returned. Enable TRACE level for more.
06:58,560 main TRACE fr.mines_stetienne.ci.sparql_generate.engine.SourcePlan:128 - Exec SOURCE http://example.com/example.xml AS ?source returned
"<?xml version=\"1.0\" encoding=\"windows-12
 ... _Package></XMI>"^^https://www.iana.org/assignments/media-types/application/xml
06:58,607 main TRACE fr.mines_stetienne.ci.sparql_generate.iterator.IteratorStreamFunctionBase:61 - Building the iterator 791408866
Exception in thread "main" java.lang.StackOverflowError
        at java.xml/org.xml.sax.helpers.AttributesImpl.addAttribute(AttributesImpl.java:393)
        at java.xml/com.sun.org.apache.xml.internal.serializer.AttributesImplSerializer.addAttribute(AttributesImplSerializer.java:113)
        at java.xml/com.sun.org.apache.xml.internal.serializer.ToStream.doAddAttributeAlways(ToStream.java:3030)
        at java.xml/com.sun.org.apache.xml.internal.serializer.ToStream.addAttributeAlways(ToStream.java:2895)
        at java.xml/com.sun.org.apache.xml.internal.serializer.SerializerBase.addAttribute(SerializerBase.java:383)
        at java.xml/com.sun.org.apache.xml.internal.serializer.ToUnknownStream.addAttribute(ToUnknownStream.java:274)
        at java.xml/com.sun.org.apache.xalan.internal.xsltc.trax.DOM2TO.parse(DOM2TO.java:200)
        ..... (above line repeats many times)
```
I have run this on Windows using the 2.0.12 release.

**Comment by maximelefrancois86** [comment]
Thanks for reporting this issue, 

Unfortunately I can't tell if/when this issue may be solved.
As a matter of fact, I don't plan on maintaining SPARQL-Generate any longer, and I think I will be archive it soon.

Instead, I am dedicating some of my time on a new exciting project: https://gitlab.com/coswot/ldpy -> https://pypi.org/project/linked-data-python/ 
This covers the use cases from SPARQL-Generate, and more.

**Comment by cgrain** [comment]
Thank you for your quick response, even though it is rather unfortunate. I was specifically looking into tooling that was usable for my peers that are familliar with SPARQL, but not so much with other (programming) languages.
