### ISSUE TITLE
PathNotFoundException on BIND with JSONPath without matching results

### ISSUE THREAD

**Issue by KMax** [sparql-generate/sparql-generate#32]
I have the following query:
```
GENERATE {
    ?employeeUri a schema:Person ;
        rdfs:label ?fullname ;
        schema:givenName ?givenName ;
        schema:familyName ?surname ;
        schema:telephone ?telephone .
}
SOURCE <./examples/smarttouch_employees.json> AS ?source
ITERATOR iter:JSONPath(?source, "$.rows[*]") AS ?employee
WHERE {
    BIND(IRI(CONCAT("http://mir-vr.com/instance/", "employee-", STR(fun:JSONPath(?employee, "$.emp_id")))) AS ?employeeUri)
    BIND(fun:JSONPath(?employee, "$.emp_surname") AS ?surname)
    BIND(fun:JSONPath(?employee, "$.emp_name") AS ?givenName)
    BIND(CONCAT(?surname, " ", ?givenName) AS ?fullname)

    BIND(STR(fun:JSONPath(?employee, "$.emp_phone")) AS ?telephone)
}
```
Some `?employee` objects don't have the `emp_phone` key, so I get the following exception which I actually don't expect:

```
com.jayway.jsonpath.PathNotFoundException: No results for path: $['emp_phone']
	at com.jayway.jsonpath.internal.path.EvaluationContextImpl.getValue(EvaluationContextImpl.java:131)
	at com.jayway.jsonpath.JsonPath.read(JsonPath.java:187)
	at com.jayway.jsonpath.internal.JsonContext.read(JsonContext.java:164)
	at com.jayway.jsonpath.internal.JsonContext.read(JsonContext.java:147)
	at com.github.thesmartenergy.sparql.generate.jena.function.library.FUN_JSONPath.exec(FUN_JSONPath.java:95)
	at org.apache.jena.sparql.function.FunctionBase2.exec(FunctionBase2.java:55)
	at org.apache.jena.sparql.function.FunctionBase.exec(FunctionBase.java:52)
	at org.apache.jena.sparql.expr.E_Function.evalSpecial(E_Function.java:64)
	at org.apache.jena.sparql.expr.ExprFunctionN.eval(ExprFunctionN.java:100)
	at org.apache.jena.sparql.expr.ExprNode.eval(ExprNode.java:93)
	at org.apache.jena.sparql.expr.ExprFunction1.eval(ExprFunction1.java:68)
	at org.apache.jena.sparql.core.VarExprList.get(VarExprList.java:106)
	at org.apache.jena.sparql.engine.iterator.QueryIterAssign.accept(QueryIterAssign.java:62)
	at org.apache.jena.sparql.engine.iterator.QueryIterProcessBinding.hasNextBinding(QueryIterProcessBinding.java:69)
	at org.apache.jena.sparql.engine.iterator.QueryIteratorBase.hasNext(QueryIteratorBase.java:114)
	at org.apache.jena.sparql.engine.iterator.QueryIteratorWrapper.hasNextBinding(QueryIteratorWrapper.java:39)
	at org.apache.jena.sparql.engine.iterator.QueryIteratorBase.hasNext(QueryIteratorBase.java:114)
	at org.apache.jena.sparql.engine.iterator.QueryIteratorWrapper.hasNextBinding(QueryIteratorWrapper.java:39)
	at org.apache.jena.sparql.engine.iterator.QueryIteratorBase.hasNext(QueryIteratorBase.java:114)
	at org.apache.jena.sparql.engine.ResultSetStream.hasNext(ResultSetStream.java:74)
	at org.apache.jena.sparql.engine.ResultSetCheckCondition.hasNext(ResultSetCheckCondition.java:55)
	at com.github.thesmartenergy.sparql.generate.jena.engine.impl.SelectPlanImpl.exec(SelectPlanImpl.java:103)
	at com.github.thesmartenergy.sparql.generate.jena.engine.impl.RootPlanImpl.exec(RootPlanImpl.java:356)
	at com.github.thesmartenergy.sparql.generate.jena.engine.impl.RootPlanImpl.lambda$exec$0(RootPlanImpl.java:347)
	at com.github.thesmartenergy.sparql.generate.jena.engine.impl.IteratorPlanImpl.lambda$null$0(IteratorPlanImpl.java:117)
	at com.github.thesmartenergy.sparql.generate.jena.iterator.IteratorFunctionBase.exec(IteratorFunctionBase.java:30)
	at com.github.thesmartenergy.sparql.generate.jena.iterator.IteratorStreamFunctionBase.exec(IteratorStreamFunctionBase.java:78)
	at com.github.thesmartenergy.sparql.generate.jena.engine.impl.IteratorPlanImpl.lambda$exec$1(IteratorPlanImpl.java:101)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at com.github.thesmartenergy.sparql.generate.jena.engine.impl.IteratorPlanImpl.exec(IteratorPlanImpl.java:98)
	at com.github.thesmartenergy.sparql.generate.jena.engine.impl.RootPlanImpl.exec(RootPlanImpl.java:346)
	at com.github.thesmartenergy.sparql.generate.jena.engine.impl.RootPlanImpl.exec(RootPlanImpl.java:352)
	at com.github.thesmartenergy.sparql.generate.jena.engine.impl.RootPlanImpl.exec(RootPlanImpl.java:327)
	at com.github.thesmartenergy.sparql.generate.jena.engine.impl.RootPlanImpl.exec(RootPlanImpl.java:302)
	at com.github.thesmartenergy.sparql.generate.jena.engine.impl.RootPlanImpl.exec(RootPlanImpl.java:287)
	at com.github.thesmartenergy.sparql.generate.jena.engine.impl.RootPlanImpl.exec(RootPlanImpl.java:185)
	at com.github.thesmartenergy.sparql.generate.jena.SPARQLGenerateCli.main(SPARQLGenerateCli.java:160)
```

I don't expect it, because in the case of an ordinary SPARQL query `?telephone` would be unbound, the query would be executed correctly, and the triples containing `?telephone` wouldn't be generated.

**Comment by maximelefrancois86** [comment]
Actually, any exception occurring at line 

```java
	at com.github.thesmartenergy.sparql.generate.jena.function.library.FUN_JSONPath.exec(FUN_JSONPath.java:95)
```

Is catched in a loop, outputed in a `debug` message:

```java
            LOG.debug("No evaluation of " + json + ", " + jsonpath, ex); // line 135
```

And then an `ExprEvalException` is thrown (which is the contract with Jena)

```java
            throw new ExprEvalException("No evaluation of " + json + ", " + jsonpath, ex); // line 136
```

So: I don't understand what is blocking for you. Isn't the exception actually catched ? Is it that you would expect the logging level for this to be lower than `debug` ?

**Comment by KMax** [comment]
Oh, I'm sorry! The exception is actually caught, I just was confused by the way it's printed in the console. It looked like the program had failed with this exception.
