### ISSUE TITLE
NPE when converting JSON

### ISSUE THREAD

**Issue by lolive** [sparql-generate/sparql-generate#41]
Hi everyone.

I have crafted a query that converts some JSON from OpenFoodFacts to RDF. 
The following query is stored in file _additives.sg_ :

```
BASE <http://example.com/>
PREFIX iter: <http://w3id.org/sparql-generate/iter/>
PREFIX fun: <http://w3id.org/sparql-generate/fn/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX crm: <http://www.cidoc-crm.org/cidoc-crm/>
PREFIX food:  <http://world-fr.openfoodfacts.org/>


GENERATE {
  ?additive a food:Additive .
  GENERATE {
        ?additive a ?additive_class .
  }
  ITERATOR iter:Split(fun:JSONPath(?en_additive_obj,"$.additives_classes.en"), ", ") AS ?en_additive_class
  WHERE {
    BIND (IRI(CONCAT("http://world-fr.openfoodfacts.org/additives/class/",REPLACE(?en_additive_class,"en:",""))) AS ?additive_class)
  } .

}
SOURCE <https://static.openfoodfacts.org/data/taxonomies/additives.json> AS ?source
ITERATOR iter:JSONPath(?source,"$.*") AS ?en_additive_obj
ITERATOR iter:JSONListKeys(?en_additive_obj) AS ?en_additive
WHERE {
    BIND (IRI(CONCAT("http://world-fr.openfoodfacts.org/additives/",REPLACE(?en_additive,"en:",""))) as ?additive)
}
```

I run this query with this simple command line:

`java -jar sparql-generate-jena.jar -q additives.sg`

But I get this error:

```
DEBUG [main] (SourcePlanImpl.java:132) - "{\"en:e160aii\":{\"efsa_evaluation_date\":{\"en\":\"2016-03-18\"},\"efsa\":{\"en\":\"http://www.efsa.europa.eu/fr/efsaj
 ... 
:sequestrant\"}}}"^^http://www.iana.org/assignments/media-types/application/json
ERROR [main] (SPARQLGenerateCli.java:162) - Error while executing the plan.
java.lang.NullPointerException
        at org.apache.jena.sparql.expr.E_Function.evalSpecial(E_Function.java:61)
        at org.apache.jena.sparql.expr.ExprFunctionN.eval(ExprFunctionN.java:100)
        at com.github.thesmartenergy.sparql.generate.jena.iterator.IteratorStreamFunctionBase.exec(IteratorStreamFunctionBase.java:74)
        at com.github.thesmartenergy.sparql.generate.jena.engine.impl.IteratorPlanImpl.lambda$exec$1(IteratorPlanImpl.java:100)
        at java.util.ArrayList.forEach(ArrayList.java:1255)
        at com.github.thesmartenergy.sparql.generate.jena.engine.impl.IteratorPlanImpl.exec(IteratorPlanImpl.java:98)
        at com.github.thesmartenergy.sparql.generate.jena.engine.impl.RootPlanImpl.exec(RootPlanImpl.java:346)
        at com.github.thesmartenergy.sparql.generate.jena.engine.impl.RootPlanImpl.exec(RootPlanImpl.java:327)
        at com.github.thesmartenergy.sparql.generate.jena.engine.impl.RootPlanImpl.exec(RootPlanImpl.java:302)
        at com.github.thesmartenergy.sparql.generate.jena.engine.impl.GenerateTemplatePlanImpl.lambda$null$1(GenerateTemplatePlanImpl.java:106)
        at java.util.ArrayList.forEach(ArrayList.java:1255)
        at com.github.thesmartenergy.sparql.generate.jena.engine.impl.GenerateTemplatePlanImpl.lambda$exec$2(GenerateTemplatePlanImpl.java:81)
        at java.util.ArrayList.forEach(ArrayList.java:1255)
        at com.github.thesmartenergy.sparql.generate.jena.engine.impl.GenerateTemplatePlanImpl.exec(GenerateTemplatePlanImpl.java:79)
        at com.github.thesmartenergy.sparql.generate.jena.engine.impl.RootPlanImpl.exec(RootPlanImpl.java:364)
        at com.github.thesmartenergy.sparql.generate.jena.engine.impl.RootPlanImpl.lambda$exec$0(RootPlanImpl.java:347)
        at com.github.thesmartenergy.sparql.generate.jena.engine.impl.IteratorPlanImpl.lambda$null$0(IteratorPlanImpl.java:122)
        at com.github.thesmartenergy.sparql.generate.jena.iterator.IteratorFunctionBase.exec(IteratorFunctionBase.java:30)
        at com.github.thesmartenergy.sparql.generate.jena.iterator.IteratorStreamFunctionBase.exec(IteratorStreamFunctionBase.java:78)
        at com.github.thesmartenergy.sparql.generate.jena.engine.impl.IteratorPlanImpl.lambda$exec$1(IteratorPlanImpl.java:100)
        at java.util.ArrayList.forEach(ArrayList.java:1255)
        at com.github.thesmartenergy.sparql.generate.jena.engine.impl.IteratorPlanImpl.exec(IteratorPlanImpl.java:98)
        at com.github.thesmartenergy.sparql.generate.jena.engine.impl.RootPlanImpl.exec(RootPlanImpl.java:346)
        at com.github.thesmartenergy.sparql.generate.jena.engine.impl.RootPlanImpl.exec(RootPlanImpl.java:352)
        at com.github.thesmartenergy.sparql.generate.jena.engine.impl.RootPlanImpl.exec(RootPlanImpl.java:327)
        at com.github.thesmartenergy.sparql.generate.jena.engine.impl.RootPlanImpl.exec(RootPlanImpl.java:302)
        at com.github.thesmartenergy.sparql.generate.jena.engine.impl.RootPlanImpl.exec(RootPlanImpl.java:287)
        at com.github.thesmartenergy.sparql.generate.jena.engine.impl.RootPlanImpl.exec(RootPlanImpl.java:185)
        at com.github.thesmartenergy.sparql.generate.jena.SPARQLGenerateCli.main(SPARQLGenerateCli.java:150)
Program finished in 0 min, 1 sec
```

Did I misused some of Sparql-Generate statements?

**Comment by infomehdi** [comment]
You can try this (adapted) query on your [additives.json](https://static.openfoodfacts.org/data/taxonomies/additives.json)
```
BASE <http://example.com/>
PREFIX iter: <http://w3id.org/sparql-generate/iter/>
PREFIX fun: <http://w3id.org/sparql-generate/fn/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX crm: <http://www.cidoc-crm.org/cidoc-crm/>
PREFIX food:  <http://world-fr.openfoodfacts.org/>


GENERATE {
  ?additive a food:Additive .
  GENERATE {
    ?additive a ?additive_class .
  }
  ITERATOR iter:Split(?en_additive_classes, ", ") AS ?en_additive_class
  WHERE {
    BIND (IRI(CONCAT("http://world-fr.openfoodfacts.org/additives/",REPLACE(?en_additive_class,"en:",""))) as ?additive_class)
    FILTER (STRLEN(?en_additive_classes)>0)
  } .
}
SOURCE <https://static.openfoodfacts.org/data/taxonomies/additives.json> AS ?source
ITERATOR iter:JSONListKeys(?source) AS ?en_additive
WHERE {
    BIND (IRI(CONCAT("http://world-fr.openfoodfacts.org/additives/",REPLACE(?en_additive,"en:",""))) as ?additive)
    BIND (fun:JSONPath(?source,CONCAT("$.",?en_additive,".additives_classes.en")) AS ?en_additive_classes)
}
```

I have tried it on a part of your file
```
{
  "en:e160aii": {
    "efsa_evaluation_date": {
      "en": "2016-03-18"
    },
    "efsa": {
      "en": "http://www.efsa.europa.eu/fr/efsajournal/doc/2593.pdf"
    },
    "additives_classes": {
      "en": "en:colour"
    },
    "efsa_evaluation_url": {
      "en": "http://dx.doi.org/10.2903/j.efsa.2016.4434"
    },
    "parents": [
      "en:e160a"
    ],
    "name": {
      "cs": "E160aii - Rostlinné karoteny",
      "sl": "E160aii - Rastlinski karoteni",
      "sk": "E160aii - Rastlinné karotény",
      "lv": "E160aii - Augu karotīni",
      "fr": "E160aii - Carotènes végétaux",
      "fi": "E160aii - Kasvikaroteenit",
      "pt": "E160aii - Carotenos provenientes de plantas",
      "da": "E160aii - Plantecarotener",
      "es": "E160aii - Carotenos de plantas",
      "lt": "E160aii - Augaliniai karotenai",
      "nl": "E160aii - Plantaardige carotenen",
      "mt": "E160aii - Karoteni tal-pjanti",
      "el": "E160aii - Φυτικα καροτενια",
      "ro": "E160aii - Caroten din plante",
      "it": "E160aii - Caroteni vegetali",
      "hu": "E160aii - Növényi karotinok",
      "de": "E160aii - Pflanzliche carotine",
      "sv": "E160aii - Karotener från växter",
      "bg": "E160aii - Растителни каротини",
      "pl": "E160aii - Karoteny otrzymywane z roślin",
      "et": "E160aii - Taimsed karoteenid",
      "en": "E160aii - Plant carotenes"
    },
    "efsa_evaluation": {
      "en": "Safety of the proposed extension of use of synthetic Beta-carotene [E 160aii] in foods for special medical purposes in young children"
    },
    "e_number": {
      "en": "160a"
    }
  },
  "en:e440aiii": {
    "e_number": {
      "en": "440a"
    },
    "parents": [
      "en:e440a"
    ],
    "name": {
      "sl": "E440aiii - E440a(iii) food additive",
      "cs": "E440aiii - E440a(iii) food additive",
      "fi": "E440aiii - E440a(iii) food additive",
      "lv": "E440aiii - E440a(iii) food additive",
      "fr": "E440aiii - Pectate de potassium",
      "sk": "E440aiii - E440a(iii) food additive",
      "da": "E440aiii - E440a(iii) food additive",
      "pt": "E440aiii - E440a(iii) food additive",
      "mt": "E440aiii - E440a(iii) food additive",
      "nl": "E440aiii - E440a(iii) food additive",
      "lt": "E440aiii - E440a(iii) food additive",
      "es": "E440aiii - E440a(iii) food additive",
      "it": "E440aiii - E440a(iii) food additive",
      "ro": "E440aiii - E440a(iii) food additive",
      "el": "E440aiii - E440a(iii) food additive",
      "sv": "E440aiii - E440a(iii) food additive",
      "bg": "E440aiii - E440a(iii) food additive",
      "de": "E440aiii - E440a(iii) food additive",
      "hu": "E440aiii - E440a(iii) food additive",
      "et": "E440aiii - E440a(iii) food additive",
      "pl": "E440aiii - E440a(iii) food additive",
      "en": "E440aiii - Potassium pectate"
    },
    "wikidata": {
      "en": "Q188154"
    },
    "additives_classes": {
      "en": "en:emulsifier, en:stabilizer, en:thickener"
    }
  },
  "en:e226": {
    "efsa_evaluation_date": {
      "en": "2016-04-14"
    },
    "efsa_evaluation": {
      "en": "Scientific Opinion on the re-evaluation of sulfur dioxide -E 220-, sodium sulfite -E 221-, sodium bisulfite -E 222-, sodium metabisulfite -E 223-, potassium metabisulfite -E 224-, calcium sulfite -E 226-, calcium bisulfite -E 227- and potassium bisulfite -E 228- as food additives"
    },
    "e_number": {
      "en": "226"
    },
    "efsa_evaluation_url": {
      "en": "http://dx.doi.org/10.2903/j.efsa.2016.4438"
    },
    "name": {
      "en": "E226 - Calcium sulphite",
      "pl": "E226 - Siarczyn wapnia",
      "et": "E226 - Kaltsiumsulfit",
      "hu": "E226 - Kalcium-szulfit",
      "de": "E226 - Calciumsulfit",
      "sv": "E226 - Kalciumsulfit",
      "bg": "E226 - Калциев сулфит",
      "ro": "E226 - Sulfit de calciu",
      "el": "E226 - Θειωδες ασβεστιο",
      "it": "E226 - Solfito di calcio",
      "nl": "E226 - Calciumsulfiet",
      "lt": "E226 - Kalcio sulfitas",
      "es": "E226 - Sulfito cálcico",
      "mt": "E226 - Sulfit tal-kalċju",
      "pt": "E226 - Sulfito de cálcio",
      "da": "E226 - Calciumsulfit",
      "lv": "E226 - Kalcija sulfīts",
      "fr": "E226 - Sulfite de calcium",
      "sk": "E226 - Siričitan vápenatý",
      "fi": "E226 - Kalsiumsulfiitti",
      "cs": "E226 - Siřičitan vápenatý",
      "sl": "E226 - Kalcijev sulfit"
    },
    "wikidata": {
      "en": "Q899410"
    }
  }
}
```

The result is

```
@base          <http://example.org/> .
@prefix xsd:   <http://www.w3.org/2001/XMLSchema#> .
@prefix iter:  <http://w3id.org/sparql-generate/iter/> .
@prefix rdfs:  <http://www.w3.org/2000/01/rdf-schema#> .
@prefix food:  <http://world-fr.openfoodfacts.org/> .
@prefix fun:   <http://w3id.org/sparql-generate/fn/> .
@prefix crm:   <http://www.cidoc-crm.org/cidoc-crm/> .

<http://world-fr.openfoodfacts.org/additives/e160aii>
        a       <http://world-fr.openfoodfacts.org/additives/colour> , food:Additive .

<http://world-fr.openfoodfacts.org/additives/e226>
        a       food:Additive .

<http://world-fr.openfoodfacts.org/additives/e440aiii>
        a       <http://world-fr.openfoodfacts.org/additives/thickener> , <http://world-fr.openfoodfacts.org/additives/stabilizer> , <http://world-fr.openfoodfacts.org/additives/emulsifier> , food:Additive .
```

I hope it is what you expected as a result.
